# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXLovePlayNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JXLovePlayNews

pod 'PPNetworkHelper', '~> 0.8.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Texture', '~> 2.3.3'
pod 'TOWebViewController', '~> 2.2.6'
pod 'JTSImageViewController', '~> 1.5.1'
pod 'YYWebImage', '~> 1.0.5'
pod 'KMNavigationBarTransition', '~> 1.0.0'
pod 'SDCycleScrollView', '~> 1.66'
pod 'MXParallaxHeader', '~> 0.6.1'
pod 'TYPagerController', '~> 1.0.2'
pod 'TYAttributedLabel', '~> 2.6.2'
pod 'JPFPSStatus', '~> 0.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'CocoaLumberjack', '~> 3.2.0' #适用于Mac和iOS的快速简单但功能强大且灵活的日志框架
pod 'MLeaksFinder', '~> 0.2.1' #在开发时，在iOS应用程序中查找内存泄漏。

end
